// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdwcvbrcwyvvpjaqydmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkd2N2YnJjd3l2dnBqYXF5ZG1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAyODMxOTcsImV4cCI6MjEwNTg1OTE5N30.86hushjQpbCXlRGBi4TzftZVGNCD6yE-KvsDiWCiQBY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});